Repository Azure/vscode-bridge-to-kubernetes, pull requests merged in 2023-08, with the labels that each got.

#62 Code coverage checks and reports
  .github/workflows/build.yml
  .gitignore
  package-lock.json
  package.json
Labels: enhancement 🧑‍🔧💡

#63 Enable codecov and build badges for visibility.
  README.md
Labels: documentation 💼

#65 update changelog
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release 🚀🎊

#68 Update deprecated packages
  package-lock.json
  package.json
  src/logger/Logger.ts
  src/tests/CommonTestObjects.ts
  src/tests/suites/AccountContextManager-Test.ts
  src/tests/suites/BridgeClientProvider-Test.ts
  src/tests/suites/DotNetClientProvider-Test.ts
  src/tests/suites/ExpectedCLIVersion-Test.ts
  src/tests/suites/KubectlClient-Test.ts
  src/tests/suites/Logger-Test.ts
  src/tests/suites/RedactUtility-Test.ts
  src/tests/suites/StringUtility-Test.ts
Labels: enhancement 🧑‍🔧💡, refactor 👨‍🚒🧑‍🔧
