Repository Azure/vscode-bridge-to-kubernetes, pull requests merged in 2024-01, with the labels that each got.

#85 Addressing the module not found errors
  package-lock.json
  package.json
  webpack.config.js
Labels: bug, enhancement 🧑‍🔧💡

#87 Bump Axios and Xml2js dependencies
  package-lock.json
  package.json
Labels: enhancement 🧑‍🔧💡, dependencies

#88 Jan 2024 release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release 🚀🎊

#89 Changes in correlation with new GH Action Permission Changes.
  .github/workflows/build.yml
  .github/workflows/publish.yml
Labels: enhancement 🧑‍🔧💡
